# Generated by Django 5.2.3 on 2025-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('marks', models.FloatField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
